### PR TITLE
#updated intl version

### PR DESCRIPTION
**Pull request by Iamstanlee**
The intl version was updated from `0.58.0` to `0.16.1` to fix comflicting issues with firebase plugins

### CODE REVIEW

**Review by nfortiz — APPROVED** [review]

**Comment by nfortiz** [comment]
Did you test the changes?

**Comment by Chappie74** [comment]
@Iamstanlee  did you? We need this update in asap

**Comment by Iamstanlee** [comment]
yes i did

**Review by AhmedNourJamalElDin — APPROVED** [review]

**Comment by AhmedNourJamalElDin** [comment]
Please merge this PR

**Pull request merged**
